# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bank-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bank-App

  target 'Bank-AppTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble-Snapshots', '~> 9.1'
	pod 'Nimble', '~> 9.2'
	pod 'Quick', '~> 4.0'
  end

end
